# -*- coding: utf-8 -*-
"""Cópia de Atividade Cloves - Lista de Exercícios em Python - Allana Aquino.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fc7sBWuAlOuA1AxoMCmm3mT9EiySGf6C
"""

print("Olá ETE PORTO DIGITAL!");

num = input("Digite um número: ");
print('O número informado foi', num);

num1 = input('Digite o primeiro número: ');
num2 = input('Digite o segundo número: ');
soma = int(num1) + int(num2)
print (soma);

bi1 = input('Digite a nota do 1º bimestre: ');
bi2 = input('Digite a nota do 2º bimestre: ');
bi3 = input('Digite a nota do 3º bimestre: ');
bi4 = input('Digite a nota do 4º bimestre: ');

media = (int(bi1) + int(bi2) + int(bi3) + int(bi4))/4

print('A média final é:', media);

me1 = input('Digite o tamanho em metros: ');

cem = int(me1)*100

print('O valor em cemtimetros é:', cem);

raio = input('Digite o tamanho do raio: ');

area = (int(raio)**2) * 3,14
print('O valor da área do circulo é:', area);

lado = input('Digite o tamanho do lado do quadrado: ');
area = (int(lado))*(int(lado))
dobro = (int(area))*2

print('O valor da área do quadrado é:', area, 'Porém o dobro é', dobro);

valor = input('Digite o valor da sua hora: ');
hora = input('Digite quantas horas você trabalha por mês? ');
total = (float(valor))*(float(hora))
print('O valor do seu salário é', total );

valor = input('Digite um valor: ');
if (int(valor)) >= 0 : 
  print ('O valor é positivo')
else :
  print('O valor é negativo')

gen = input('Digite seu gênero: ');

if gen == 'm' or gen == 'M':
  print('M - Masculino')
elif gen == 'f' or gen =='F':
    print('F - Feminino')
else :
  print('Sexo inválido')